const LEVELS = [
  // MONDO 1 – OGGETTI SEMPLICI / PALLONCINI / FORME
  {
    id: 1,
    world: 1,
    name: "Palloncino rosso",
    shape: "balloon",
    balloons: 3,
    balloonSpeed: 40,
    balloonSize: 1.0,
    arrows: 40,
    timeLimit: 50,
    pattern: "horizontal"
  },
  {
    id: 2,
    world: 1,
    name: "Cuore",
    shape: "heart",
    balloons: 4,
    balloonSpeed: 50,
    balloonSize: 1.0,
    arrows: 45,
    timeLimit: 48,
    pattern: "horizontal"
  },
  {
    id: 3,
    world: 1,
    name: "Stella",
    shape: "star",
    balloons: 5,
    balloonSpeed: 60,
    balloonSize: 0.95,
    arrows: 50,
    timeLimit: 46,
    pattern: "horizontal"
  },
  {
    id: 4,
    world: 1,
    name: "Nuvola",
    shape: "cloud",
    balloons: 5,
    balloonSpeed: 70,
    balloonSize: 0.9,
    arrows: 55,
    timeLimit: 44,
    pattern: "horizontal"
  },
  {
    id: 5,
    world: 1,
    name: "Quadrato",
    shape: "square",
    balloons: 6,
    balloonSpeed: 80,
    balloonSize: 0.9,
    arrows: 60,
    timeLimit: 42,
    pattern: "horizontal"
  },
  {
    id: 6,
    world: 1,
    name: "Triangolo",
    shape: "triangle",
    balloons: 7,
    balloonSpeed: 90,
    balloonSize: 0.85,
    arrows: 65,
    timeLimit: 40,
    pattern: "zigzag"
  },
  {
    id: 7,
    world: 1,
    name: "Diamante",
    shape: "diamond",
    balloons: 8,
    balloonSpeed: 95,
    balloonSize: 0.8,
    arrows: 70,
    timeLimit: 38,
    pattern: "zigzag"
  },
  {
    id: 8,
    world: 1,
    name: "Ciambella",
    shape: "donut",
    balloons: 9,
    balloonSpeed: 100,
    balloonSize: 0.8,
    arrows: 75,
    timeLimit: 36,
    pattern: "zigzag"
  },
  {
    id: 9,
    world: 1,
    name: "Bersaglio",
    shape: "target",
    balloons: 10,
    balloonSpeed: 105,
    balloonSize: 0.75,
    arrows: 80,
    timeLimit: 34,
    pattern: "mixed"
  },
  {
    id: 10,
    world: 1,
    name: "Bomba (cartoon)",
    shape: "bomb",
    balloons: 12,
    balloonSpeed: 110,
    balloonSize: 0.75,
    arrows: 90,
    timeLimit: 32,
    pattern: "mixed"
  },

  // MONDO 2 – FRUTTA
  {
    id: 11,
    world: 2,
    name: "Mela",
    shape: "apple",
    balloons: 8,
    balloonSpeed: 115,
    balloonSize: 0.95,
    arrows: 100,
    timeLimit: 32,
    pattern: "horizontal"
  },
  {
    id: 12,
    world: 2,
    name: "Arancia",
    shape: "orange",
    balloons: 9,
    balloonSpeed: 120,
    balloonSize: 0.95,
    arrows: 105,
    timeLimit: 31,
    pattern: "horizontal"
  },
  {
    id: 13,
    world: 2,
    name: "Limone",
    shape: "lemon",
    balloons: 10,
    balloonSpeed: 120,
    balloonSize: 0.9,
    arrows: 110,
    timeLimit: 30,
    pattern: "horizontal"
  },
  {
    id: 14,
    world: 2,
    name: "Anguria",
    shape: "watermelon",
    balloons: 10,
    balloonSpeed: 125,
    balloonSize: 0.9,
    arrows: 115,
    timeLimit: 30,
    pattern: "zigzag"
  },
  {
    id: 15,
    world: 2,
    name: "Fragola",
    shape: "strawberry",
    balloons: 11,
    balloonSpeed: 130,
    balloonSize: 0.9,
    arrows: 120,
    timeLimit: 29,
    pattern: "zigzag"
  },
  {
    id: 16,
    world: 2,
    name: "Ciliegie",
    shape: "cherry",
    balloons: 12,
    balloonSpeed: 130,
    balloonSize: 0.85,
    arrows: 125,
    timeLimit: 28,
    pattern: "zigzag"
  },
  {
    id: 17,
    world: 2,
    name: "Pera",
    shape: "pear",
    balloons: 12,
    balloonSpeed: 135,
    balloonSize: 0.85,
    arrows: 130,
    timeLimit: 28,
    pattern: "mixed"
  },
  {
    id: 18,
    world: 2,
    name: "Ananas",
    shape: "pineapple",
    balloons: 13,
    balloonSpeed: 140,
    balloonSize: 0.85,
    arrows: 135,
    timeLimit: 27,
    pattern: "mixed"
  },
  {
    id: 19,
    world: 2,
    name: "Banana",
    shape: "banana",
    balloons: 14,
    balloonSpeed: 145,
    balloonSize: 0.8,
    arrows: 140,
    timeLimit: 26,
    pattern: "mixed"
  },
  {
    id: 20,
    world: 2,
    name: "Grappolo d'uva",
    shape: "grape",
    balloons: 15,
    balloonSpeed: 150,
    balloonSize: 0.8,
    arrows: 145,
    timeLimit: 26,
    pattern: "mixed"
  },

  // MONDO 3 – SPAZIO / FANTASY
  {
    id: 21,
    world: 3,
    name: "Pianeta",
    shape: "planet",
    balloons: 10,
    balloonSpeed: 150,
    balloonSize: 0.9,
    arrows: 150,
    timeLimit: 25,
    pattern: "zigzag"
  },
  {
    id: 22,
    world: 3,
    name: "Luna",
    shape: "moon",
    balloons: 11,
    balloonSpeed: 155,
    balloonSize: 0.9,
    arrows: 155,
    timeLimit: 25,
    pattern: "zigzag"
  },
  {
    id: 23,
    world: 3,
    name: "Sole",
    shape: "sun",
    balloons: 12,
    balloonSpeed: 160,
    balloonSize: 0.9,
    arrows: 160,
    timeLimit: 24,
    pattern: "zigzag"
  },
  {
    id: 24,
    world: 3,
    name: "Razzo",
    shape: "rocket",
    balloons: 13,
    balloonSpeed: 165,
    balloonSize: 0.85,
    arrows: 165,
    timeLimit: 24,
    pattern: "mixed"
  },
  {
    id: 25,
    world: 3,
    name: "UFO",
    shape: "ufo",
    balloons: 14,
    balloonSpeed: 170,
    balloonSize: 0.85,
    arrows: 170,
    timeLimit: 23,
    pattern: "mixed"
  },
  {
    id: 26,
    world: 3,
    name: "Cometa",
    shape: "comet",
    balloons: 15,
    balloonSpeed: 170,
    balloonSize: 0.85,
    arrows: 175,
    timeLimit: 23,
    pattern: "mixed"
  },
  {
    id: 27,
    world: 3,
    name: "Meteora",
    shape: "meteor",
    balloons: 16,
    balloonSpeed: 175,
    balloonSize: 0.8,
    arrows: 180,
    timeLimit: 22,
    pattern: "mixed"
  },
  {
    id: 28,
    world: 3,
    name: "Cristallo magico",
    shape: "crystal",
    balloons: 16,
    balloonSpeed: 180,
    balloonSize: 0.8,
    arrows: 185,
    timeLimit: 22,
    pattern: "mixed"
  },
  {
    id: 29,
    world: 3,
    name: "Buco nero",
    shape: "blackhole",
    balloons: 17,
    balloonSpeed: 185,
    balloonSize: 0.8,
    arrows: 190,
    timeLimit: 22,
    pattern: "mixed"
  },
  {
    id: 30,
    world: 3,
    name: "Corona del Re",
    shape: "crown",
    balloons: 18,
    balloonSpeed: 190,
    balloonSize: 0.8,
    arrows: 200,
    timeLimit: 22,
    pattern: "mixed"
  }
];
